fire/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('answer/', views.ask, name='ask'),
    path('', views.home, name='home'),
    # path('questions/', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # # path('index_result/', views.IndexResultsView.as_view(), name='index_result'),
    # path('index_result/', views.index_result, name='index_result'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Answer, Question

from .documents import QuestionDocument

import random
import pandas as pd
import numpy as np
import re


class IndexView(generic.ListView):
    template_name = 'polls/questions.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/questions.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = question.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a answer.",
        })
    else:
        selected_answer.votes += 1
        selected_answer.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


# 主页
def home(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html')


# 结果页
def index_result(request):
    # question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/index_result.html')


# 提问模块(提取动植物种类)
def ask(request):
    reg = "[^A-Za-z\u4e00-\u9fa5]" #用于去除类别中的标点
    question_text = request.POST['question'].strip()                                    # 获取提的问题
    print('question_text:', question_text)
    ap = 'we'                                                                           # 用于储存动植物名称，默认为it
    cat = pd.read_csv('../babistep_retrieval-based/creatures.csv')                 # 读取动植物列表(需要手动修改绝对路径)
    category = cat.columns                                                              # 获取表头
    dicat = {}                                                                          # 把表头以字典形式存储
    i=0
    for c in category:
        dicat[i] = re.sub(reg, ' ', c)
        i=i+1
    dic = {}                                                                            # 把动植物名称与种类对应生成字典
    m = cat.shape[0]                                                                    # 获取总行数
    n = cat.shape[1]                                                                    # 获取总列数
    for p in range(n):
        for q in range(m):
            dic[cat.iloc[[q],[p]].values[0][0]] = dicat[p]
            q=q+1
        p=p+1
    t = str(question_text)
    for p in range(n):                                                                  # 用csv中所有动植物名称和问题进行匹配
        p=p+1
        for q in range(m):
            q=q+1
            c = str(cat.iloc[[q-1],[p-1]].values[0][0])                                 #去除连接符
            cc = c.split()
            ccc = " ".join(cc)
            flag = re.search(ccc,t)                                     
            if bool(flag) == True:
                ap = c
                question_text = t.replace(c,dic[c])
                break
        else:
            continue
        break
    print('question_text(modified):', question_text)
    answer = get_similar_question_answer(question_text)  # 获取答案
    answer.answer_text = ap + " has a gift for you at " + answer.answer_text
    # 查找是否有人问过相同问题
    questions = Question.objects.filter(question_text=question_text)
    questions_len = len(questions)
    # print('questions_len:', questions_len)
    if questions_len > 0:
        # 相同问题记录
        question = questions[random.randrange(questions_len)]
        question.votes += 1
        question.save()
        print('find:', question.id, ' ', question.question_text)
    else:
        # 新问题保存
        question = Question(question_text=question_text, pub_date=timezone.now())
        question.save()
        print('save:', question.id)

    return render(request, 'polls/index_result.html', {'question': question, 'answer': answer})


# 获取相似问题答案（a标签超级链接）
def get_similar_question_answer(question_text):
    answer = Answer()  # 空答案初始化
    # seg_list = jieba.cut(question_text)  # 默认是精确模式
    # print("jeiba:" + "%".join(seg_list))
    # 查找是否有人问过相似问题
    s = QuestionDocument.search().query("match", question_text=question_text)
    qs = s.to_queryset()
    # qs is just a django queryset and it is called with order_by to keep the same order as the elasticsearch result
    print("qs:", qs)
    for q in qs:
        print(q.question_text, '-', q.id, '-', q.answer_set.all())
        if len(q.answer_set.all()) > 0:
            answer = get_best_answer(q)
            break
    return answer


# 获取最佳答案
def get_best_answer(question):
    answer = Answer()  # 空答案初始化
    answers = question.answer_set.all()
    answers_len = len(answers)
    if answers_len > 0:
        # 在相同问题中随机选则votes最多的答案
        answer = answers.order_by('votes').last()
        print('answer:', answer.id, ' ', answer.answer_text)
    return answer

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for answer in question.answer_set.all %}
        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
        <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>search page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/popover.css' %}" charset="UTF-8">

    <link href="https://fonts.googleapis.com/css?family=ZCOOL+KuaiLe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+SC&display=swap" rel="stylesheet">
</head>

<body>
    <main>
        <div class="background">
            <div class="purple"></div>
            <div class="green"></div>
            <div class="red"></div>
            <div class="blue"></div>
        </div>
        <div class="content">
            <div class="logo">
                <h1>小小步</h1>
            </div>
            <form id="search" action="{% url 'polls:ask' %}" method="post">
                {% csrf_token %}
                <div class="search-bar">
                    <input class="search-input" name="question" type="text">
                    <input type="image" aria-hidden="true"
                            class="svg-icon search-right-icon"
                            src="{% static 'polls/img/lightbulb.svg' %}" alt="lightbulb icon"
                    />
                </div>
                <div class="info">
                    <img id="trigger" data-popover-target="info-popover" aria-hidden="true" class="svg-icon info-icon" src="{% static 'polls/img/round-info-button.svg' %}">
                    <template data-popover="info-popover">
                        使用提示：本网站提供市场上已有日常生活产品或服务的趣味对比
                        举例：用户输入“洛杉矶市区最好吃的海南鸡饭是哪家？”
                        得到回答“三亚市区最本地的5星级酒店是XXXXX酒店”
                        团队希望帮助用户发掘生活中有趣的选择。
                    </template>
                </div>
            </form>
        </div>
        <footer>
            <div>
                <p>小小步 © 2020 &middot;<a href="http://www.beian.miit.gov.cn">粤ICP备19147212号琼</a><a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=46020402000087"><img src="{% static 'polls/img/authority.png' %}" />琼公网安备 46020402000087号</a></p>
                <p>Icons made by <a href="https://www.flaticon.com/authors/good-ware" title="Good Ware">Good Ware</a>, <a href="https://www.flaticon.com/authors/gregor-cresnar" title="Good Ware">Gregor Cresnar</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></p>
            </div>
        </footer>
    </main>
<script type="text/javascript" src="{% static 'polls/popover.js' %}"> </script>
</body>

</html>

polls/templates/polls/index_result.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search result page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="{% static 'polls/popover.css' %}">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+KuaiLe&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+SC&display=swap" rel="stylesheet">
</head>

<body>
    <main>
        <div class="background">
            <div class="purple">
            </div>
            <div class="green">
            </div>
            <div class="red">
            </div>
            <div class="blue">
            </div>
        </div>
        <div class="content">
            <div class="logo">
                <h1>小小步</h1>
            </div>
            <div class="active-area">
                <form id="search" action="">
                    <div class="search-bar">
                        <input class="search-input-result" value="{{ answer.answer_text }}{% if not answer.answer_text %}小小步还没学会这个问题呢，等我问下师父再来告诉你答案哈~{% endif %}" disabled />
                        <a href="{% url 'polls:home' %}">
                            <img aria-hidden="true"
                                class="svg-icon search-left-icon"
                                src="{% static 'polls/img/previous.svg' %}"
                                alt="arrow-back"
                            />
                        </a>
                    </div>
                    <div class="info">
                    <img id="trigger" data-popover-target="info-popover" aria-hidden="true" class="svg-icon info-icon" src="{% static 'polls/img/round-info-button.svg' %}">
                        <template data-popover="info-popover">
                            使用提示：本网站提供市场上已有日常生活产品或服务的趣味对比
                            举例：用户输入“洛杉矶市区最好吃的海南鸡饭是哪家？”
                            得到回答“三亚市区最本地的5星级酒店是XXXXX酒店”
                            团队希望帮助用户发掘生活中有趣的选择。
                        </template>
                    </div>
                </form>
                <form id="vote" action="">
                    <div class="rate-answer" >
                        <div class="emoji">
                            <a href="#" onclick="disappear(event)"><img src="{% static 'polls/img/emoji/laughing.svg' %}" alt="emoji-laughing"></a>
                        </div>
                        <div class="emoji">
                            <a href="#" onclick="disappear(event)"><img src="{% static 'polls/img/emoji/wink.svg' %}" alt="emoji-wink"></a>
                        </div>
                        <div class="emoji">
                            <a href="#" onclick="disappear(event)"><img src="{% static 'polls/img/emoji/sad.svg' %}" alt="emoji-sad"></a>
                        </div>
                        <div class="emoji">
                            <a href="#" onclick="disappear(event)"><img src="{% static 'polls/img/emoji/crying.svg' %}" alt="emoji-crying"></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <footer>
            <div>
              <p>小小步 © 2020 &middot;<a href="http://www.beian.miit.gov.cn">粤ICP备19147212号琼</a><a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=46020402000087"><img src="{% static 'polls/img/authority.png' %}" />琼公网安备 46020402000087号</a></p>
                <p>Icons made by <a href="https://www.flaticon.com/authors/good-ware" title="Good Ware">Good Ware</a>, <a href="https://www.flaticon.com/authors/gregor-cresnar" title="Good Ware">Gregor Cresnar</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></p>
            </div>
        </footer>
    </main>
<script type="text/javascript" src="{% static 'polls/popover.js' %}"> </script>
<script type="text/javascript">
    function disappear(e) {
        e.preventDefault();
        const emoji = document.getElementsByClassName('emoji')
        for (i = 0; i < emoji.length; i++) {
            emoji[i].style.display = 'none';
        }
    }
</script>
</body>

</html>

polls/templates/polls/questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.answer_text }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>